name: Cache Workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache7273dae
        uses: actions/cache@v4
        with:
          path: ~/.cache/demo
          key: cache-7273dae

      - name: prime-cache-7273dae
        run: echo "Cache hit? ${{ steps.cache7273dae.outputs.cache-hit }}"
